# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: hotel_reservation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
         echo "# REPORTS" >> report.md
         echo "## metrics" >> report.md
         roc_auc_curve.png >> report.md
         cml-send-comment report.md
